add-swiper-controls
SoftRyzen-internship/confetti pull request #4
Opened 2024-01-08 13:31 UTC by A-Novychenko

Додав компонент "Кнопки слайдера"
Встановив залежності:  styled-components,"swiper"

2024-01-08 17:10 UTC, opanchen requested changes

2024-01-08 17:10 UTC, opanchen commented on src/data/sliderControlsData.json
думаю, краще додати в файлі common.json окреме поле 'slider' і там описати лейбли для контролсів
це маленький блок інформації - навіщо заводити окремий файл?

2024-01-08 17:10 UTC, opanchen commented on tailwind.config.ts
> +        'color-ctrl-btn': '#FFFFFF',
цей колір краще винести вище до бекграундів і назвати якось універсально (наприклад, 'secondary') - він використовується на цілих секціях, а самі кнопки по дефолту мають наслідувати bg батьківського елементу (ну або просто пропиши в їх стилях нову назву цього білого кольору)

2024-01-08 17:10 UTC, opanchen commented on tailwind.config.ts
> +        'color-ctrl-btn-accent': '#FFEFF0',
вже є вище (color-bg-primary)

2024-01-08 17:10 UTC, opanchen commented on src/components/ui/SliderControls/SliderControls.tsx
> +        justify-center rounded-full border border-solid border-color-ctrl-btn-border bg-color-ctrl-btn transition-all hover:border-transparent hover:bg-color-ctrl-btn-accent
для transition додай утилітний клас в globals.css, про який ми домовились з командою, і юзай його

2024-01-09 07:51 UTC, A-Novychenko commented on src/data/sliderControlsData.json
Виправив. Переніс у common.json

2024-01-09 07:51 UTC, A-Novychenko commented on tailwind.config.ts
> +        'color-ctrl-btn': '#FFFFFF',
Виправив. Переніс, назвав secondary

2024-01-09 07:51 UTC, A-Novychenko commented on tailwind.config.ts
> +        'color-ctrl-btn-accent': '#FFEFF0',
Виправив

2024-01-09 07:52 UTC, A-Novychenko commented on src/components/ui/SliderControls/SliderControls.tsx
> +        justify-center rounded-full border border-solid border-color-ctrl-btn-border bg-color-ctrl-btn transition-all hover:border-transparent hover:bg-color-ctrl-btn-accent
Поки що зробив по іншому, і рекомендую всім так переробити. В tailwind це реалізовано краще, потрібно лише налаштувати конфіг і transition-all transition-colors ... будуть використовувати ці налаштування, а де треба щось унікальне точково можна перебити тими ж класами tailwind. Конфіг я налаштував. Для того щоб працювало достатньо використовувати transition-all або transition-colors чи що там ще потрібно. 
Після налаштування конфіга тепер так наприклад для transition-all: 
.transition-all {
    transition-property: all;
    transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
    transition-duration: 300ms;
}

2024-01-09 14:34 UTC, opanchen approved these changes

2024-01-09 14:34 UTC, merged